
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mehdi Fll
 */
public class Menu extends javax.swing.JFrame {

    int gametype;
    int niveau;
    String pioncolor;
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.pvp.setVisible(true);
        this.Black.setVisible(false);
        this.Easy.setVisible(false);
        this.Hard.setVisible(false);
        this.Medium.setVisible(false);
        this.White.setVisible(false);
                this.jPanel7.setVisible(false);
                this.jPanel3.setVisible(false);

        Color c = new Color(255, 255, 255);
        this.getContentPane().setBackground(c);
       
        try {
            File selectedFile = new File("users.txt");
            FileInputStream fileIn = new FileInputStream(selectedFile);
            ObjectInputStream in = new ObjectInputStream(fileIn);
            ArrayList<String> text = ((ArrayList<String>) in.readObject());
            String[] model = new String[text.size()];
            for (int i=0;i<text.size();i++){
                model[i]=text.get(i);
            }
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(model));
            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(model));

            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
                
                
                

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        pvc = new javax.swing.JButton();
        pvp = new javax.swing.JButton();
        cg = new javax.swing.JButton();
        Easy1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Easy = new javax.swing.JButton();
        Medium = new javax.swing.JButton();
        Hard = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Black = new javax.swing.JButton();
        White = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cg1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(235, 200, 175));
        jPanel4.setLayout(new java.awt.GridLayout(4, 0, 0, 10));

        pvc.setBackground(new java.awt.Color(235, 200, 175));
        pvc.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        pvc.setForeground(new java.awt.Color(97, 64, 64));
        pvc.setText("Player vs Computer");
        pvc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));
        //pvc.setOpaque(false);
        pvc.setContentAreaFilled(false);
        // pvc.setBorderPainted(false);
        pvc.setBorder(null);
        pvc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pvcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pvcMouseExited(evt);
            }
        });
        pvc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pvcActionPerformed(evt);
            }
        });
        jPanel4.add(pvc);

        pvp.setBackground(new java.awt.Color(235, 200, 175));
        pvp.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        pvp.setForeground(new java.awt.Color(97, 64, 64));
        pvp.setText("Player1 vs Player2");
        pvp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));
        pvp.setOpaque(false);
        pvp.setContentAreaFilled(false);
        pvp.setBorder(null);
        pvp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pvpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pvpMouseExited(evt);
            }
        });
        pvp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pvpActionPerformed(evt);
            }
        });
        jPanel4.add(pvp);

        cg.setBackground(new java.awt.Color(235, 200, 175));
        cg.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        cg.setForeground(new java.awt.Color(97, 64, 64));
        cg.setText("Continue game");
        cg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));
        cg.setOpaque(false);
        cg.setContentAreaFilled(false);
        cg.setBorder(null);
        cg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cgMouseExited(evt);
            }
        });
        cg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgActionPerformed(evt);
            }
        });
        jPanel4.add(cg);

        Easy1.setBackground(new java.awt.Color(235, 200, 175));
        Easy1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Easy1.setForeground(new java.awt.Color(97, 64, 64));
        Easy1.setText("Users");
        Easy1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));
        Easy1.setOpaque(false);
        Easy1.setContentAreaFilled(false);
        Easy1.setBorder(null);
        Easy1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Easy1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Easy1MouseExited(evt);
            }
        });
        Easy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Easy1ActionPerformed(evt);
            }
        });
        jPanel4.add(Easy1);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 180, 240));

        jPanel5.setBackground(new java.awt.Color(235, 200, 175));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        Easy.setBackground(new java.awt.Color(235, 200, 175));
        Easy.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Easy.setForeground(new java.awt.Color(97, 64, 64));
        Easy.setText("Easy");
        Easy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));
        Easy.setOpaque(false);
        Easy.setContentAreaFilled(false);
        Easy.setBorder(null);
        Easy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EasyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EasyMouseExited(evt);
            }
        });
        Easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EasyActionPerformed(evt);
            }
        });
        jPanel5.add(Easy);

        Medium.setBackground(new java.awt.Color(235, 200, 175));
        Medium.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Medium.setForeground(new java.awt.Color(97, 64, 64));
        Medium.setText("Medium");
        Medium.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));
        Medium.setOpaque(false);
        Medium.setContentAreaFilled(false);
        Medium.setBorder(null);
        Medium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MediumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MediumMouseExited(evt);
            }
        });
        Medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediumActionPerformed(evt);
            }
        });
        jPanel5.add(Medium);

        Hard.setBackground(new java.awt.Color(235, 200, 175));
        Hard.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Hard.setForeground(new java.awt.Color(97, 64, 64));
        Hard.setText("Hard");
        Hard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));
        Hard.setOpaque(false);
        Hard.setContentAreaFilled(false);
        Hard.setBorder(null);
        Hard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HardMouseExited(evt);
            }
        });
        Hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardActionPerformed(evt);
            }
        });
        jPanel5.add(Hard);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 430, 60));

        jPanel6.setBackground(new java.awt.Color(235, 200, 175));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 25, 0));

        Black.setBackground(new java.awt.Color(235, 200, 175));
        Black.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Black.setForeground(new java.awt.Color(97, 64, 64));
        Black.setText("Black");
        Black.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));
        Black.setOpaque(false);
        Black.setContentAreaFilled(false);
        Black.setBorder(null);
        Black.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BlackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BlackMouseExited(evt);
            }
        });
        Black.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackActionPerformed(evt);
            }
        });
        jPanel6.add(Black);

        White.setBackground(new java.awt.Color(235, 200, 175));
        White.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        White.setForeground(new java.awt.Color(97, 64, 64));
        White.setText("White");
        White.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));
        White.setOpaque(false);
        White.setContentAreaFilled(false);
        White.setBorder(null);
        White.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WhiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WhiteMouseExited(evt);
            }
        });
        White.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WhiteActionPerformed(evt);
            }
        });
        jPanel6.add(White);

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 370, 60));

        jPanel1.setBackground(new java.awt.Color(235, 200, 175));
        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 50, -1));

        jPanel2.setBackground(new java.awt.Color(235, 200, 175));
        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, 50));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(97, 64, 64));
        jLabel1.setText("GOMOKU GAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 310, -1));

        jPanel3.setBackground(new java.awt.Color(235, 200, 175));
        jPanel3.setOpaque(false);

        cg1.setBackground(new java.awt.Color(235, 200, 175));
        cg1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        cg1.setForeground(new java.awt.Color(97, 64, 64));
        cg1.setText("Start");
        cg1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));
        cg1.setOpaque(false);
        cg1.setOpaque(false);
        cg1.setContentAreaFilled(false);
        cg1.setBorder(null);
        cg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cg1MouseExited(evt);
            }
        });
        cg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cg1ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(235, 200, 175));
        jPanel7.setLayout(new java.awt.GridLayout(2, 0, 20, 0));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(97, 64, 64));
        jLabel2.setText("Player1");
        jPanel7.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(97, 64, 64));
        jLabel3.setText("Player2");
        jPanel7.add(jLabel3);

        jComboBox1.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jComboBox1.setOpaque(false);
        jComboBox1.setRequestFocusEnabled(false);
        jPanel7.add(jComboBox1);

        jComboBox2.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setOpaque(false);
        jPanel7.add(jComboBox2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(cg1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 42, Short.MAX_VALUE)
                .addComponent(cg1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 290, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pvcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pvcActionPerformed
        this.gametype = 1;
        this.pvc.setVisible(false);
        this.pvp.setVisible(false);
        this.Black.setVisible(false);
        this.Easy.setVisible(true);
        this.Hard.setVisible(true);
        this.Medium.setVisible(true);
        this.White.setVisible(false);
        this.cg.setVisible(false);
        jPanel4.setOpaque(false);
        jPanel4.setBorder(null);
        jPanel4.setVisible(false);
        jPanel5.setOpaque(true);
    }//GEN-LAST:event_pvcActionPerformed

    private void cgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cgMouseClicked
        jPanel4.setOpaque(false);
        jPanel4.setBorder(null);
        jPanel4.setVisible(false);
        jPanel5.setOpaque(true);

// TODO add your handling code here:
    }//GEN-LAST:event_cgMouseClicked

    private void cgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cgMouseEntered
        cg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));      // TODO add your handling code here:
    }//GEN-LAST:event_cgMouseEntered

    private void cgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cgMouseExited
        cg.setBorder(null);      // TODO add your handling code here:
    }//GEN-LAST:event_cgMouseExited

    private void pvpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pvpActionPerformed
        this.gametype = 2;
        this.jPanel4.setVisible(false);
        this.jPanel3.setVisible(true);
                this.jPanel3.setOpaque(true);
                this.jPanel7.setVisible(true);
                this.jComboBox1.setVisible(true);
                
                this.jLabel2.setVisible(true);
                
                       this.cg1.setVisible(true);
    
    }//GEN-LAST:event_pvpActionPerformed

    private void MediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediumActionPerformed
        this.niveau = 2;
        this.Black.setVisible(true);
        this.Easy.setVisible(false);
        this.Hard.setVisible(false);
        this.Medium.setVisible(false);
        this.White.setVisible(true);
        jPanel5.setOpaque(false);
        jPanel5.setBorder(null);
        jPanel5.setVisible(false);
        jPanel6.setOpaque(true);
    }//GEN-LAST:event_MediumActionPerformed

    private void EasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EasyActionPerformed
        this.niveau = 1;
        this.Black.setVisible(true);
        this.Easy.setVisible(false);
        this.Hard.setVisible(false);
        this.Medium.setVisible(false);
        this.White.setVisible(true);
        jPanel5.setOpaque(false);
        jPanel5.setBorder(null);
        jPanel5.setVisible(false);
        jPanel6.setOpaque(true);
    }//GEN-LAST:event_EasyActionPerformed

    private void HardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardActionPerformed
        this.niveau = 3;
        this.Black.setVisible(true);
        this.Easy.setVisible(false);
        this.Hard.setVisible(false);
        this.Medium.setVisible(false);
        this.White.setVisible(true);
        jPanel5.setOpaque(false);
        jPanel5.setBorder(null);
        jPanel5.setVisible(false);
        jPanel6.setOpaque(true);
    }//GEN-LAST:event_HardActionPerformed

    private void WhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WhiteActionPerformed
        this.pioncolor = "white";
        this.jPanel6.setVisible(false);
                this.jPanel4.setVisible(false);
        this.jPanel3.setVisible(true);
                this.jPanel3.setOpaque(true);
                this.jPanel7.setVisible(true);
                this.jComboBox1.setVisible(true);
                this.jComboBox2.setVisible(false);
                this.jLabel2.setVisible(true);
                this.jLabel3.setVisible(false);
                       this.cg1.setVisible(true);

        //Game game = new Game(gametype, niveau, pioncolor);

      //  this.setVisible(false);
       // game.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_WhiteActionPerformed

    private void BlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackActionPerformed
        this.pioncolor = "black";
        this.jPanel6.setVisible(false);
                this.jPanel4.setVisible(false);
        this.jPanel3.setVisible(true);
                this.jPanel3.setOpaque(true);
                this.jPanel7.setVisible(true);
                this.jComboBox1.setVisible(true);
                this.jComboBox2.setVisible(false);
                this.jLabel2.setVisible(true);
                this.jLabel3.setVisible(false);
                       this.cg1.setVisible(true);

    }//GEN-LAST:event_BlackActionPerformed

    private void pvcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvcMouseEntered
        pvc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));      // TODO add your handling code here:
    }//GEN-LAST:event_pvcMouseEntered

    private void pvcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvcMouseExited
        pvc.setBorder(null);      // TODO add your handling code here:
    }//GEN-LAST:event_pvcMouseExited

    private void pvpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvpMouseEntered
        pvp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));      // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_pvpMouseEntered

    private void pvpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvpMouseExited
        pvp.setBorder(null);      // TODO add your handling code here:
    }//GEN-LAST:event_pvpMouseExited

    private void HardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HardMouseEntered
        Hard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));      // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_HardMouseEntered

    private void HardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HardMouseExited
        Hard.setBorder(null);      // TODO add your handling code here:
    }//GEN-LAST:event_HardMouseExited

    private void EasyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EasyMouseEntered
        Easy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));      // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_EasyMouseEntered

    private void EasyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EasyMouseExited
        Easy.setBorder(null);      // TODO add your handling code here:
    }//GEN-LAST:event_EasyMouseExited

    private void MediumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MediumMouseEntered
        Medium.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));      // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_MediumMouseEntered

    private void MediumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MediumMouseExited
        Medium.setBorder(null);      // TODO add your handling code here:
    }//GEN-LAST:event_MediumMouseExited

    private void BlackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlackMouseEntered
        Black.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));      // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_BlackMouseEntered

    private void BlackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlackMouseExited
        Black.setBorder(null);      // TODO add your handling code here:
    }//GEN-LAST:event_BlackMouseExited

    private void WhiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WhiteMouseEntered
        White.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));      // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_WhiteMouseEntered

    private void WhiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WhiteMouseExited
        White.setBorder(null);      // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_WhiteMouseExited

    private void cgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgActionPerformed
        // Let's deserialize an Object
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        File selectedFile;

        //int returnValue = jfc.showOpenDialog(null);
        int returnValue = jfc.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            selectedFile = jfc.getSelectedFile();
            System.out.println(selectedFile.getAbsolutePath());

            try {
                FileInputStream fileIn = new FileInputStream(selectedFile);
                ObjectInputStream in = new ObjectInputStream(fileIn);
                /*System.out.println(in.readObject().getClass());
                System.out.println(in.readObject().getClass());
                System.out.println(in.readObject().getClass());
                System.out.println(in.readObject().getClass());
                System.out.println(in.readObject().getClass());*/

                LinkedList<GomokuPosition> l = (LinkedList<GomokuPosition>) in.readObject();
                gametype = (int) in.readObject();
                niveau = (int) in.readObject();
                boolean turn = (Boolean) in.readObject();
                pioncolor = (String) in.readObject();
                Game game = new Game(l.getLast(), gametype, niveau, pioncolor);
                if (gametype == 1) {
                    game.getGrille2().drawBoardType1(l.getLast());
                    this.setVisible(false);
                    game.setVisible(true);
                    /* for (int i = 0; i < l.size(); i++) {
                        System.out.println(l.get(i));
                        game.getGrille2().drawBoardType1(l.get(i));
                        this.setVisible(false);
                        game.setVisible(true);

                    }*/

                } else {
                    game.getGrille2().drawBoardType2(l.getLast());
                    this.setVisible(false);
                    game.setVisible(true);

                }
                in.close();
                fileIn.close();

            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cgActionPerformed

    private void Easy1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Easy1MouseEntered
        Easy1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));      // TODO add your handling code here:
    }//GEN-LAST:event_Easy1MouseEntered

    private void Easy1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Easy1MouseExited
Easy1.setBorder(null);     }//GEN-LAST:event_Easy1MouseExited

    private void Easy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Easy1ActionPerformed
        try {
            Users Users = new Users();
            Users.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Easy1ActionPerformed

    private void cg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cg1MouseClicked
 
        String player1 = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
        String player2="";
        if(gametype==2) player2 = jComboBox2.getItemAt(jComboBox2.getSelectedIndex());
        Game game = new Game(gametype, niveau, pioncolor, player1, player2);
        System.out.println(player1+" "+ player2);
        this.setVisible(false);
        game.setVisible(true);
       // TODO add your handling code here:
    }//GEN-LAST:event_cg1MouseClicked

    private void cg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cg1MouseEntered
        cg1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 64, 64), 4, true));      // TODO add your handling code here:
    }//GEN-LAST:event_cg1MouseEntered

    private void cg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cg1MouseExited
        cg1.setBorder(null);      // TODO add your handling code here:
    }//GEN-LAST:event_cg1MouseExited

    private void cg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cg1ActionPerformed

                   // TODO add your handling code here:
    }//GEN-LAST:event_cg1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Black;
    private javax.swing.JButton Easy;
    private javax.swing.JButton Easy1;
    private javax.swing.JButton Hard;
    private javax.swing.JButton Medium;
    private javax.swing.JButton White;
    private javax.swing.JButton cg;
    private javax.swing.JButton cg1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton pvc;
    private javax.swing.JButton pvp;
    // End of variables declaration//GEN-END:variables
}
